src/Entity/Encadrement.php
<?php

namespace App\Entity;

use App\Repository\EncadrementRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EncadrementRepository::class)]
class Encadrement
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $type_referent = null;

    #[ORM\ManyToOne(inversedBy: 'encadrements')]
    private ?Formateur $formateur = null;

    #[ORM\ManyToOne(inversedBy: 'encadrements')]
    private ?Session $session = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTypeReferent(): ?string
    {
        return $this->type_referent;
    }

    public function setTypeReferent(string $type_referent): static
    {
        $this->type_referent = $type_referent;

        return $this;
    }

    public function getFormateur(): ?Formateur
    {
        return $this->formateur;
    }

    public function setFormateur(?Formateur $formateur): static
    {
        $this->formateur = $formateur;

        return $this;
    }

    public function getSession(): ?Session
    {
        return $this->session;
    }

    public function setSession(?Session $session): static
    {
        $this->session = $session;

        return $this;
    }

    public function __toString()
    {
        return $this->formateur->prenom." ".$this->formateur->nom." : ".$this->type_referent;
    }
}

src/Entity/Session.php
<?php

namespace App\Entity;

use App\Repository\SessionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SessionRepository::class)]
class Session
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $titreSession = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $accroche = null;

    #[ORM\Column]
    private ?int $nbPlaces = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateDebut = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateFin = null;

    #[ORM\ManyToOne(inversedBy: 'sessions')]
    private ?Formation $formation = null;

    /**
     * @var Collection<int, Encadrement>
     */
    #[ORM\OneToMany(targetEntity: Encadrement::class, mappedBy: 'session')]
    private Collection $encadrements;

    /**
     * @var Collection<int, Inscription>
     */
    #[ORM\OneToMany(targetEntity: Inscription::class, mappedBy: 'session', cascade: ['persist'], orphanRemoval: true)]
    private Collection $inscriptions;

    /**
     * @var Collection<int, Sondage>
     */
    #[ORM\OneToMany(targetEntity: Sondage::class, mappedBy: 'session')]
    private Collection $sondages;

    /**
     * @var Collection<int, Planification>
     */
    #[ORM\OneToMany(targetEntity: Planification::class, mappedBy: 'session', cascade: ['persist'], orphanRemoval: true)]
    private Collection $planifications;


    public function __construct()
    {
        $this->encadrements = new ArrayCollection();
        $this->inscriptions = new ArrayCollection();
        $this->sondages = new ArrayCollection();
        $this->planifications = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitreSession(): ?string
    {
        return $this->titreSession;
    }

    public function setTitreSession(string $titreSession): static
    {
        $this->titreSession = $titreSession;

        return $this;
    }

    public function getAccroche(): ?string
    {
        return $this->accroche;
    }

    public function setAccroche(?string $accroche): static
    {
        $this->accroche = $accroche;

        return $this;
    }

    public function getNbPlaces(): ?int
    {
        return $this->nbPlaces;
    }

    public function setNbPlaces(int $nbPlaces): static
    {
        $this->nbPlaces = $nbPlaces;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->dateDebut;
    }

    public function setDateDebut(\DateTimeInterface $dateDebut): static
    {
        $this->dateDebut = $dateDebut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->dateFin;
    }

    public function setDateFin(\DateTimeInterface $dateFin): static
    {
        $this->dateFin = $dateFin;

        return $this;
    }

    public function getFormation(): ?Formation
    {
        return $this->formation;
    }

    public function setFormation(?Formation $formation): static
    {
        $this->formation = $formation;

        return $this;
    }

    /**
     * @return Collection<int, Encadrement>
     */
    public function getEncadrements(): Collection
    {
        return $this->encadrements;
    }

    public function addEncadrement(Encadrement $encadrement): static
    {
        if (!$this->encadrements->contains($encadrement)) {
            $this->encadrements->add($encadrement);
            $encadrement->setSession($this);
        }

        return $this;
    }

    public function removeEncadrement(Encadrement $encadrement): static
    {
        if ($this->encadrements->removeElement($encadrement)) {
            // set the owning side to null (unless already changed)
            if ($encadrement->getSession() === $this) {
                $encadrement->setSession(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Inscription>
     */
    public function getInscriptions(): Collection
    {
        return $this->inscriptions;
    }

    public function addInscription(Inscription $inscription): static
    {
        if (!$this->inscriptions->contains($inscription)) {
            $this->inscriptions->add($inscription);
            $inscription->setSession($this);
        }

        return $this;
    }

    public function removeInscription(Inscription $inscription): static
    {
        if ($this->inscriptions->removeElement($inscription)) {
            // set the owning side to null (unless already changed)
            if ($inscription->getSession() === $this) {
                $inscription->setSession(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Sondage>
     */
    public function getSondages(): Collection
    {
        return $this->sondages;
    }

    public function addSondage(Sondage $sondage): static
    {
        if (!$this->sondages->contains($sondage)) {
            $this->sondages->add($sondage);
            $sondage->setSession($this);
        }

        return $this;
    }

    public function removeSondage(Sondage $sondage): static
    {
        if ($this->sondages->removeElement($sondage)) {
            // set the owning side to null (unless already changed)
            if ($sondage->getSession() === $this) {
                $sondage->setSession(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Planification>
     */
    public function getPlanifications(): Collection
    {
        return $this->planifications;
    }

    public function addPlanification(Planification $planification): static
    {
        if (!$this->planifications->contains($planification)) {
            $this->planifications->add($planification);
            $planification->setSession($this);
        }

        return $this;
    }

    public function removePlanification(Planification $planification): static
    {
        if ($this->planifications->removeElement($planification)) {
            // set the owning side to null (unless already changed)
            if ($planification->getSession() === $this) {
                $planification->setSession(null);
            }
        }

        return $this;
    }


    // cette méthode permet d'obtenir le prix total payé par tous les apprenants inscrits à une session.
    // il existe aussi un moyen d'obtenir le prix total directement dans la vue (voir mon commentaire dans la vue de détails de session)
    public function getTotalPrice(): string
    {
        $somme = 0;
    
        foreach ($this->inscriptions as $inscription) {
            $somme += $inscription->getPrix(); 
        }

        return $somme." euros";
    }


    // cette méthode permet de passer d'une durée exprimée en minutes à une durée exprimée en heures et en minutes :
    // $hours est le quotient de la division (intdiv) et $minutes est le reste de la division (% = opérateur modulo)
    // sprintf() est une fonction qui formate une chaîne de caractères : "%d" est un espace réservé qui sera remplacé par un nombre entier et justement les valeurs de $hours et $minutes sont insérées dans ces espaces réservés, dans l'ordre où elles apparaissent après la chaîne.
    /*
    public function getFormattedDuration(): string
    {
        $hours = intdiv($this->dureeTotale, 60);
        $minutes = $this->dureeTotale % 60;

        if ($hours > 0 && $minutes > 0) {
            return sprintf("%d heures et %d minutes", $hours, $minutes);
        } elseif ($hours > 0) {
            return sprintf("%d heures", $hours);
        } else {
            return sprintf("%d minutes", $minutes);
        }
    }
    */


    // Cette méthode permet d'additionner toutes les durées (dans la table planification) pour tous les modules enseignés dans une session donnée
    // On initialise à zéro puis on ajoute pour cet objet Session là toutes les durées des planifications qui le concernent
    // Ensuite, on reprend la méthode au dessus pour convertir proprement en heures et minutes (repris de l'entité Planification)
    public function getFormattedDuration(): string
    {
        $somme = 0;
    
        foreach ($this->planifications as $planification) {
            $somme += $planification->getDuree();
        }

        $hours = intdiv($somme, 60);
        $minutes = $somme % 60;

        // return sprintf("%d heures et %d minutes", $hours, $minutes); -> affiche " x heures et 0 minutes" -> avec des conditions, on évite le souci.
        if ($hours > 0 && $minutes > 0) {
            return sprintf("%d heures et %d minutes", $hours, $minutes);
        } elseif ($hours > 0) {
            return sprintf("%d heures", $hours);
        } else {
            return sprintf("%d minutes", $minutes);
        }

    }


    /* cette méthode permet d'afficher le jour et l'heure de début et de fin de la session de formation
    public function getDatesSession(): string
    {
        return "du ".$this->dateDebut->format('d/m/Y') ." à ". $this->dateDebut->format('H:i')." au ". $this->dateFin->format('d/m/Y')." à ". $this->dateFin->format('H:i');
    }
    */

    // cette méthode permet d'afficher le jour et l'heure de début et de fin de la session de formation
    // mieux que la version précédente du dessus car je tiens compte des sessions qui se déroulent sur une seule journée
    public function getDatesSession(): string
    {
        
        if ($this->dateDebut->format('d/m/Y') == $this->dateFin->format('d/m/Y')) {
            return "le ".$this->dateDebut->format('d/m/Y') ." de ". $this->dateDebut->format('H:i')." à ". $this->dateFin->format('H:i');
        } else {

templates/session/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détails d'une session{% endblock %}

{% block meta_description %}La vue de détails d'une session présente dans votre annuaire, avec les informations nécessaires au fonctionnement de l'outil de gestion administrative FORMA'GESTION.{% endblock %}

{% block body %}

<div class="accueil-sous-cont">

    {# messages flash #}
    {% for label, messages in app.flashes %}
    {% for message in messages %}
        <div class="flash-{{ label }}">
            {{ message }}
        </div>
    {% endfor %}
    {% endfor %}

    <h1 class="session-h1">Session : {{ session.formation.nomFormation }}</h1>
    <h3 class="session-h3">du {{ session.dateDebut|date("d/m/Y") }} au {{ session.dateFin|date("d/m/Y") }}</h3>

    <div class="sous-cont">
        
        <div class="details-fiches">

            <div class="fiche-gauche">
    
                <div class="fiche-champ">
                    <span class="fiche-violet">Type :</span>&nbsp;<div>{{ session.formation.type|upper }}</div>
                </div>
                
                <div class="fiche-champ">
                    <span class="fiche-violet">Modalités :</span>&nbsp;<div>en {{ session.formation.modalites|lower }}</div>
                </div>
    
                <div class="fiche-champ">
                    <span class="fiche-violet">Durée totale :</span>&nbsp;<div>{{ session.formattedDuration }}</div>
                </div>
    
                <div class="fiche-champ">
                    <span class="fiche-violet">Prix total :</span>&nbsp;<div>{{ session.totalPrice }}</div> {# autre méthode possible : {% set somme = 0 %} {% for inscription in session.inscriptions %}{% set somme = somme + inscription.prix %}{% endfor %}{{ somme }} euros<br> #}
                </div>
    
                <div class="fiche-champ">
                    <span class="fiche-violet">Nb de places restantes :</span>&nbsp;<div>{{ session.nbPlaces  -  session.inscriptions|length }}</div>
                </div>
    
            </div>
        
            <div class="fiche-droite">
    
                {% for encadrement in session.encadrements %}
    
                    <div class="fiche-champ">
                        <span class="fiche-violet">référent {{ encadrement.typeReferent }} :</span>&nbsp;<div>
                            <a href="{{ path('show_formateur', {'id' : encadrement.formateur.id}) }}"><span class="fiche-orange"><i class="fa-solid fa-up-right-from-square"></i>{{ encadrement.formateur.prenom|capitalize }} {{ encadrement.formateur.nom|upper }}</span></a><br>
                            {{ encadrement.formateur.email }}<br>
                            {{ encadrement.formateur.tel }}
                        </div>
    
                    </div>
    
                {% endfor %}
                
            </div>
    
        </div>
        
    
        <h2>
            Apprenants inscrits à la session :  
        </h2>
    
        {#
        {% for inscription in session.inscriptions %}
    
            <a href="{{ path('show_apprenant', {'id' : inscription.apprenant.id}) }}">{{ inscription.apprenant.prenom|capitalize }} {{ inscription.apprenant.nom|upper }} {{ inscription.apprenant.email }} {{ inscription.apprenant.tel }}{% if inscription.apprenant.societe is not null %} {{ inscription.apprenant.societe.raisonSociale }}{% else %} -{% endif %}</a><br>
            
        {% endfor %}
        #}
    
    
        {% set apprenants_trouves = false %} {# On initialise une variable pour savoir si on a trouvé des apprenants inscrits (en réalité, si on trouve une inscription) en cours #}
    
        {% for inscription in session.inscriptions %}
    
            {% if inscription %} {# on vérifie qu'on trouve au moins une inscription dans la collection d'inscriptions de la session #}
                {% set apprenants_trouves = true %} {# On met la variable à true dès qu'on trouve un apprenant #}
                <table class="session-details-table">
                    <thead>
                        <tr>
                            <th class="clickable-row" data-href="{{ path('show_apprenant', {'id' : inscription.apprenant.id}) }}">
                                <a href="{{ path('show_apprenant', {'id' : inscription.apprenant.id}) }}">Prénom, NOM</a>
                            </th>
                            <th class="clickable-row" data-href="{{ path('show_apprenant', {'id' : inscription.apprenant.id}) }}">
                                <a href="{{ path('show_apprenant', {'id' : inscription.apprenant.id}) }}">Email</a>
                            </th>
                            <th class="clickable-row" data-href="{{ path('show_apprenant', {'id' : inscription.apprenant.id}) }}">
                                <a href="{{ path('show_apprenant', {'id' : inscription.apprenant.id}) }}">Téléphone</a>
                            </th>
                            <th class="clickable-row" data-href="{{ path('show_apprenant', {'id' : inscription.apprenant.id}) }}">
                                <a href="{{ path('show_apprenant', {'id' : inscription.apprenant.id}) }}">Société</a>
                            </th>
                            <th class="clickable-row" data-href="{{ path('show_apprenant', {'id' : inscription.apprenant.id}) }}">
                                <a href="{{ path('show_apprenant', {'id' : inscription.apprenant.id}) }}">Prix (en euros)</a>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="clickable-row" data-href="{{ path('show_apprenant', {'id' : inscription.apprenant.id}) }}">
                                <a href="{{ path('show_apprenant', {'id' : inscription.apprenant.id}) }}">{{ inscription.apprenant.prenom|capitalize }} {{ inscription.apprenant.nom|upper }}</a>
                            </td>
                            <td class="clickable-row" data-href="{{ path('show_apprenant', {'id' : inscription.apprenant.id}) }}">
                                <a href="{{ path('show_apprenant', {'id' : inscription.apprenant.id}) }}">{{ inscription.apprenant.email|lower }}</a>
                            </td>
                            <td class="clickable-row" data-href="{{ path('show_apprenant', {'id' : inscription.apprenant.id}) }}">
                                <a href="{{ path('show_apprenant', {'id' : inscription.apprenant.id}) }}">{{ inscription.apprenant.tel }}</a>
                            </td>
                            <td class="clickable-row" data-href="{{ path('show_apprenant', {'id' : inscription.apprenant.id}) }}">
                                <a href="{{ path('show_apprenant', {'id' : inscription.apprenant.id}) }}">{% if inscription.apprenant.societe is not null %} {{ inscription.apprenant.societe.raisonSociale }}{% else %} -{% endif %}</a>
                            </td>
                            <td class="clickable-row" data-href="{{ path('show_apprenant', {'id' : inscription.apprenant.id}) }}">
                                <a href="{{ path('show_apprenant', {'id' : inscription.apprenant.id}) }}">{{ inscription.prix }}</a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            {% endif %}
            
        {% endfor %}
    
        {% if not apprenants_trouves %} {# Après la boucle for, on vérifie si la variable 'apprenants_trouves' est toujours false. Si c'est le cas, cela signifie qu'aucun apprenant (en réalité, aucune inscription) n'a été trouvé, et donc on affiche le message "Aucun apprenant de l'annuaire inscrit à cette session". #}
            <div class="msg-vide">Aucun apprenant de l'annuaire inscrit à cette session</div>
        {% endif %}
    
    
        <h2>Modules enseignés pendant la session :</h2>
    
        <div class="details-modules">
    
            {% for planification in session.planifications %}
    
            <a href="{{ path('construction') }}" class="clickable-div"> {# <a href="{{ path('show_module', {'id' : planification.module.id}) }}" class="clickable-div"></a> #}
                <div class="fiche-module">
                    <div class="fiche-champ">
                        <span class="fiche-violet">Module {{ loop.index }}&nbsp;:</span>&nbsp;<div>{{ planification.module.nomModule }}</div>
                    </div>
    
                    <div class="fiche-champ">
                        <span class="fiche-violet-mini">Description&nbsp;:</span>&nbsp;<div class="fiche-gris-mini">{{ planification.module.description }}</div>
                    </div>
    
                    <div class="fiche-champ">
                        <span class="fiche-violet">Durée&nbsp;:</span>&nbsp;<div>{{ planification.formattedDuration02 }}</div>
                    </div>
                    <div class="fiche-champ">
                        <span class="fiche-violet"></span><div class="fiche-gris-maxi">{{ planification.datesModule }}</div> {# ancienne méthode -> du {{ planification.dateDebut|date("d/m/Y") }} à {{ planification.dateDebut|date("H:i") }} au {{ planification.dateFin|date("d/m/Y") }} à {{ planification.dateFin|date("H:i") }}<br> #}
                    </div>
                </div>
            </a>
    
            {% endfor %}
    
        </div>
    
    
        <div class="position-rose">
            {% if is_granted('ROLE_ADMIN') %}<a class="btn btn-rose" href="{{ path('delete_session', {'id' : session.id}) }}"><i class="fa-solid fa-trash"></i>Supprimer</a>{% endif %} {# bouton pour supprimer la session #}
    
            {% if is_granted('ROLE_ADMIN') %}<a class="btn btn-rose" href="{{ path('edit_session', {'id' : session.id}) }}"><i class="fa-solid fa-pen-to-square"></i>Editer</a>{% endif %} {# bouton pour éditer la session #}
    
            <a class="btn btn-rose" href="{{ path('app_session') }}"><i class="fa-solid fa-right-from-bracket"></i>Quitter</a> {# bouton pour retourner à la liste des sessions #}
        </div>

    </div>

</div>

{% endblock %}


{#
public function getFormattedDuration()

Twig fournit un objet loop dans les boucles for, avec plusieurs propriétés utiles :
loop.index0 : commence à 0 et s'incrémente à chaque itération.
loop.index : commence à 1 et s'incrémente aussi à chaque itération.
#}

templates/session/suivi_index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Suivi administratif : liste des sessions{% endblock %}

{% block meta_description %}La liste complète des sessions dans la section de suivi administratif de l'outil de gestion.{% endblock %}

{% block body %}

<div class="accueil-sous-cont">

    <h1>Sessions</h1>
    <h3>Suivi administratif des sessions en cours de traitement</h3>

    <div class="sous-cont">
        {# {% for session in sessions %}

        <a href="{{ path('show_session', {'id' : session.id}) }}">{{ session.titreSession }} nb actuel d'inscrits : {{ session.inscriptions | length }} {{ session.dateDebut | date("d/m/Y") }} {{ session.dateFin | date("d/m/Y") }} {{ session.formation.type }} {{ session.formation.modalites }} {{ session.nbPlaces }}</a>
        <a class="btn btn-gris" href="{{ path('edit_session', {'id' : session.id}) }}">M</a> -> bouton pour éditer la session
        <a class="btn btn-gris" href="{{ path('delete_session', {'id' : session.id}) }}">X</a> <br> -> bouton pour supprimer la session
        
    {% endfor %} #}

    {% if sessions|length > 0 %} <!-- dans le contexte PHP classique, on utilise count() pour savoir combien d'éléments existent dans la collection, dans le contexte TWIG, on utilise le filtre length -->

        <table class="apprenants-table">
            <thead>
                <tr>
                    <th>
                        Référence de la session<br>Nombre actuel d'inscrits
                    </th>
                    <th>
                        Date de début
                    </th>
                    <th>
                        Date de fin
                    </th>
                    <th>
                        Type
                    </th>
                    <th>
                        Modalité
                    </th>
                    <th>
                        Nb de places
                    </th>
                    <th>
                        Prix global de la session
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for session in sessions %}
                    <tr>
                        <td class="clickable-row" data-href="{{ path('suivi_show_session', {'id' : session.id}) }}">
                            <a href="{{ path('suivi_show_session', {'id' : session.id}) }}">{{ session.titreSession }}<br>
                            <span class="mini-rose">{{ session.inscriptions|length }} apprenants inscrits</span></a>
                        </td>
                        <td class="clickable-row" data-href="{{ path('suivi_show_session', {'id' : session.id}) }}">
                            <a href="{{ path('suivi_show_session', {'id' : session.id}) }}">{{ session.dateDebut|date("d/m/Y") }}</a>
                        </td>
                        <td class="clickable-row" data-href="{{ path('suivi_show_session', {'id' : session.id}) }}">
                            <a href="{{ path('suivi_show_session', {'id' : session.id}) }}">{{ session.dateFin|date("d/m/Y") }}</a>
                        </td>
                        <td class="clickable-row" data-href="{{ path('suivi_show_session', {'id' : session.id}) }}">
                            <a href="{{ path('suivi_show_session', {'id' : session.id}) }}">{{ session.formation.type|upper }}</a>
                        </td>
                        <td class="clickable-row" data-href="{{ path('suivi_show_session', {'id' : session.id}) }}">
                            <a href="{{ path('suivi_show_session', {'id' : session.id}) }}">{{ session.formation.modalites|capitalize }}</a>
                        </td>
                        <td class="clickable-row" data-href="{{ path('suivi_show_session', {'id' : session.id}) }}">
                            <a href="{{ path('suivi_show_session', {'id' : session.id}) }}">{{ session.nbPlaces }}</a>
                        </td>
                        <td class="clickable-row" data-href="{{ path('suivi_show_session', {'id' : session.id}) }}">
                            <a href="{{ path('suivi_show_session', {'id' : session.id}) }}">{{ session.totalPrice }}</a> {# méthode function getTotalPrice() de Session.php #}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

    {% else %}

        <div>Aucun session n'est présente dans la base de données.</div>

    {% endif %}

    </div>

</div>

{% endblock %}

{# 
{{ session.inscriptions | length }} revient à compter le nombre d'éléments compris dans la collection d'inscriptions de la session donnée (sachant qu'une inscription vaut un apprenant inscrit !)
#}