src/Entity/Encadrement.php
<?php

namespace App\Entity;

use App\Repository\EncadrementRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EncadrementRepository::class)]
class Encadrement
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $type_referent = null;

    #[ORM\ManyToOne(inversedBy: 'encadrements')]
    private ?Formateur $formateur = null;

    #[ORM\ManyToOne(inversedBy: 'encadrements')]
    private ?Session $session = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTypeReferent(): ?string
    {
        return $this->type_referent;
    }

    public function setTypeReferent(string $type_referent): static
    {
        $this->type_referent = $type_referent;

        return $this;
    }

    public function getFormateur(): ?Formateur
    {
        return $this->formateur;
    }

    public function setFormateur(?Formateur $formateur): static
    {
        $this->formateur = $formateur;

        return $this;
    }

    public function getSession(): ?Session
    {
        return $this->session;
    }

    public function setSession(?Session $session): static
    {
        $this->session = $session;

        return $this;
    }

    public function __toString()
    {
        return $this->formateur->prenom." ".$this->formateur->nom." : ".$this->type_referent;
    }
}

src/Entity/Session.php
<?php

namespace App\Entity;

use App\Repository\SessionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SessionRepository::class)]
class Session
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $titreSession = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $accroche = null;

    #[ORM\Column]
    private ?int $nbPlaces = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateDebut = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateFin = null;

    #[ORM\ManyToOne(inversedBy: 'sessions')]
    private ?Formation $formation = null;

    /**
     * @var Collection<int, Encadrement>
     */
    #[ORM\OneToMany(targetEntity: Encadrement::class, mappedBy: 'session')]
    private Collection $encadrements;

    /**
     * @var Collection<int, Inscription>
     */
    #[ORM\OneToMany(targetEntity: Inscription::class, mappedBy: 'session', cascade: ['persist'], orphanRemoval: true)]
    private Collection $inscriptions;

    /**
     * @var Collection<int, Sondage>
     */
    #[ORM\OneToMany(targetEntity: Sondage::class, mappedBy: 'session')]
    private Collection $sondages;

    /**
     * @var Collection<int, Planification>
     */
    #[ORM\OneToMany(targetEntity: Planification::class, mappedBy: 'session', cascade: ['persist'], orphanRemoval: true)]
    private Collection $planifications;


    public function __construct()
    {
        $this->encadrements = new ArrayCollection();
        $this->inscriptions = new ArrayCollection();
        $this->sondages = new ArrayCollection();
        $this->planifications = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitreSession(): ?string
    {
        return $this->titreSession;
    }

    public function setTitreSession(string $titreSession): static
    {
        $this->titreSession = $titreSession;

        return $this;
    }

    public function getAccroche(): ?string
    {
        return $this->accroche;
    }

    public function setAccroche(?string $accroche): static
    {
        $this->accroche = $accroche;

        return $this;
    }

    public function getNbPlaces(): ?int
    {
        return $this->nbPlaces;
    }

    public function setNbPlaces(int $nbPlaces): static
    {
        $this->nbPlaces = $nbPlaces;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->dateDebut;
    }

    public function setDateDebut(\DateTimeInterface $dateDebut): static
    {
        $this->dateDebut = $dateDebut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->dateFin;
    }

    public function setDateFin(\DateTimeInterface $dateFin): static
    {
        $this->dateFin = $dateFin;

        return $this;
    }

    public function getFormation(): ?Formation
    {
        return $this->formation;
    }

    public function setFormation(?Formation $formation): static
    {
        $this->formation = $formation;

        return $this;
    }

    /**
     * @return Collection<int, Encadrement>
     */
    public function getEncadrements(): Collection
    {
        return $this->encadrements;
    }

    public function addEncadrement(Encadrement $encadrement): static
    {
        if (!$this->encadrements->contains($encadrement)) {
            $this->encadrements->add($encadrement);
            $encadrement->setSession($this);
        }

        return $this;
    }

    public function removeEncadrement(Encadrement $encadrement): static
    {
        if ($this->encadrements->removeElement($encadrement)) {
            // set the owning side to null (unless already changed)
            if ($encadrement->getSession() === $this) {
                $encadrement->setSession(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Inscription>
     */
    public function getInscriptions(): Collection
    {
        return $this->inscriptions;
    }

    public function addInscription(Inscription $inscription): static
    {
        if (!$this->inscriptions->contains($inscription)) {
            $this->inscriptions->add($inscription);
            $inscription->setSession($this);
        }

        return $this;
    }

    public function removeInscription(Inscription $inscription): static
    {
        if ($this->inscriptions->removeElement($inscription)) {
            // set the owning side to null (unless already changed)
            if ($inscription->getSession() === $this) {
                $inscription->setSession(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Sondage>
     */
    public function getSondages(): Collection
    {
        return $this->sondages;
    }

    public function addSondage(Sondage $sondage): static
    {
        if (!$this->sondages->contains($sondage)) {
            $this->sondages->add($sondage);
            $sondage->setSession($this);
        }

        return $this;
    }

    public function removeSondage(Sondage $sondage): static
    {
        if ($this->sondages->removeElement($sondage)) {
            // set the owning side to null (unless already changed)
            if ($sondage->getSession() === $this) {
                $sondage->setSession(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Planification>
     */
    public function getPlanifications(): Collection
    {
        return $this->planifications;
    }

    public function addPlanification(Planification $planification): static
    {
        if (!$this->planifications->contains($planification)) {
            $this->planifications->add($planification);
            $planification->setSession($this);
        }

        return $this;
    }

    public function removePlanification(Planification $planification): static
    {
        if ($this->planifications->removeElement($planification)) {
            // set the owning side to null (unless already changed)
            if ($planification->getSession() === $this) {
                $planification->setSession(null);
            }
        }

        return $this;
    }


    // cette méthode permet d'obtenir le prix total payé par tous les apprenants inscrits à une session.
    // il existe aussi un moyen d'obtenir le prix total directement dans la vue (voir mon commentaire dans la vue de détails de session)
    public function getTotalPrice(): string
    {
        $somme = 0;
    
        foreach ($this->inscriptions as $inscription) {
            $somme += $inscription->getPrix(); 
        }

        return $somme." euros";
    }


    // cette méthode permet de passer d'une durée exprimée en minutes à une durée exprimée en heures et en minutes :
    // $hours est le quotient de la division (intdiv) et $minutes est le reste de la division (% = opérateur modulo)
    // sprintf() est une fonction qui formate une chaîne de caractères : "%d" est un espace réservé qui sera remplacé par un nombre entier et justement les valeurs de $hours et $minutes sont insérées dans ces espaces réservés, dans l'ordre où elles apparaissent après la chaîne.
    /*
    public function getFormattedDuration(): string
    {
        $hours = intdiv($this->dureeTotale, 60);
        $minutes = $this->dureeTotale % 60;

        if ($hours > 0 && $minutes > 0) {
            return sprintf("%d heures et %d minutes", $hours, $minutes);
        } elseif ($hours > 0) {
            return sprintf("%d heures", $hours);
        } else {
            return sprintf("%d minutes", $minutes);
        }
    }
    */


    // Cette méthode permet d'additionner toutes les durées (dans la table planification) pour tous les modules enseignés dans une session donnée
    // On initialise à zéro puis on ajoute pour cet objet Session là toutes les durées des planifications qui le concernent
    // Ensuite, on reprend la méthode au dessus pour convertir proprement en heures et minutes (repris de l'entité Planification)
    public function getFormattedDuration(): string
    {
        $somme = 0;
    
        foreach ($this->planifications as $planification) {
            $somme += $planification->getDuree();
        }

        $hours = intdiv($somme, 60);
        $minutes = $somme % 60;

        // return sprintf("%d heures et %d minutes", $hours, $minutes); -> affiche " x heures et 0 minutes" -> avec des conditions, on évite le souci.
        if ($hours > 0 && $minutes > 0) {
            return sprintf("%d heures et %d minutes", $hours, $minutes);
        } elseif ($hours > 0) {
            return sprintf("%d heures", $hours);
        } else {
            return sprintf("%d minutes", $minutes);
        }

    }


    /* cette méthode permet d'afficher le jour et l'heure de début et de fin de la session de formation
    public function getDatesSession(): string
    {
        return "du ".$this->dateDebut->format('d/m/Y') ." à ". $this->dateDebut->format('H:i')." au ". $this->dateFin->format('d/m/Y')." à ". $this->dateFin->format('H:i');
    }
    */

    // cette méthode permet d'afficher le jour et l'heure de début et de fin de la session de formation
    // mieux que la version précédente du dessus car je tiens compte des sessions qui se déroulent sur une seule journée
    public function getDatesSession(): string
    {
        
        if ($this->dateDebut->format('d/m/Y') == $this->dateFin->format('d/m/Y')) {
            return "le ".$this->dateDebut->format('d/m/Y') ." de ". $this->dateDebut->format('H:i')." à ". $this->dateFin->format('H:i');
        } else {

templates/document/attestation_assiduite.html.twig
{% extends 'base03.html.twig' %}

{% block title %}Document administratif : attestation d'assiduité{% endblock %}

{% block meta_description %}Le document administratif 'attestation d'assiduité' généré automatiquement par FORMA'GESTION pour chaque apprenant ayant participé à une session.{% endblock %}

{% block body %}

<div class="accueil-sous-cont">

    {# logo du haut de la page #}
    <div class="doc-header">
        {% if entreprise is not null and entreprise.logoFilename is not empty %}  {# on ajoute une vérification pour éviter une erreur si l'entreprise n'existe pas ou si le logo n'est pas encore choisi #}
            <img src="{{ path('logo_display', { filename: entreprise.logoFilename }) }}" alt="Logo de l'entreprise {{ entreprise.raisonSociale }}">
        {% endif %}
    </div>

    <h1>ATTESTATION D'ASSIDUITÉ</h1>

    <div class="sous-cont">

        <p class="saut-ligne">
            Je 
            {% if representant.sexe == 'M' %} 
                soussigné, 
            {% elseif representant.sexe == 'F' %} 
                soussignée, 
            {% else %} 
                soussigné(e), 
            {% endif %}, 
            {{ representant.prenom|capitalize }} {{ representant.nom|upper  }},<br>
            agissant en qualité de {{ representant.fonction|lower }} de la société {{ entreprise.raisonSociale }}, organisme de formation dont la déclaration d'activité est enregistrée sous le numéro {{ entreprise.numDeclaActivite }} auprès du préfet de la région {{ entreprise.prefectureRegion }},
        </p>
    
        <p class="saut-ligne">
            atteste que :
        </p>
    
        <p class="saut-ligne">
            {% if apprenant.sexe == 'M' %}
                Monsieur
            {% elseif apprenant.sexe == 'F' %}
                Madame
            {% else %}
                L'apprenant
            {% endif %}
            {{ apprenant.prenom|capitalize }} {{ apprenant.nom|upper }},<br>
            {% if societe is not null %}
                {% if apprenant.sexe == 'M' %}
                    salarié
                {% elseif apprenant.sexe == 'F' %}
                    salariée
                {% else %}
                    salarié(e)
                {% endif %} de l'entreprise {{ societe.raisonSociale }},<br>
            située au {{ societe.adresseSiege }} - {{ societe.codePostalSiege }} {{ societe.villeSiege }},<br>
            {% endif %}
        </p>

        <p class="saut-ligne">
            a suivi la formation :
        </p>
    
        <h2>{{ session.formation.nomFormation }}</h2>
    
        <div>
            qui s'est déroulée {{ session.datesSession }} :<br>
            <ul>
                <li>
                    {% if session.formation.modalites == 'présentiel' %}
                        en présence (salle de formation), pour une durée de <span class="reponse01"></span> sur une durée prévue de {{ session.formattedDuration }}.
                    {% elseif session.formation.modalites == 'distanciel' %}
                        à distance, de manière synchrone (classe virtuelle) pour une durée de <span class="reponse01"></span> sur une durée prévue de {{ session.formattedDuration }}.
                    {% else %}
                        à distance, de manière asynchrone (e-learning) pour une durée de <span class="reponse01"></span> sur une durée prévue de {{ session.formattedDuration }}.
                    {% endif %}
                </li>
            </ul>
        </div>
    
        <h3>
            Nombre d'apprenants ayant participé à ladite session de formation :
        </h3>
        <p>
            {{ session.inscriptions|length }}
        </p>
    
        <h3>
            Modalités d'organisation de l'action (en présence, à distance synchrone, à distance asynchrone, etc.) :
        </h3>
        <p>
            {{ session.formation.programme.moyensEnca }}
        </p>
    
        <h3>
            Modalités d'accompagnement (ressources en ligne, visioconférence, téléphone, SMS, etc.) :
        </h3>
        <p>
            {{ session.formation.programme.moyensTech }}
        </p>
    
        <h3>
            Résultats de l'évaluation des acquis jalonnant ou terminant la formation (examen, test, contrôle continu, etc.) :
        </h3>
        <div> 
            <div class="reponse02"></div>
        </div>
    
        <div class="comment">
            Ce document ne se substitue pas :
            <ul>
                <li>
                    aux feuilles d'émargement, signées à la demi-journée par le stagiaire et le formateur, qui doivent être jointes pour les formations dispensées en présentiel ou en distanciel synchrone.
                </li>
                <li>
                    aux relevés de connexion signés par le stagiaire pour les formations dispensées en distanciel asynchrone.
                </li>
            </ul> 
            
        </div>
    
        <div class="saut-ligne">
            Fait à {{ entreprise.villeSiege|capitalize }}, le {{ 'now'|date("d-m-Y") }}
        </div>
    
        <div class="signatures saut-ligne">
            <div>
                <p>
                    Cachet et signature<br>
                    du responsable du dispensateur de formation<br>
                    {% if representant.sexe == 'M' %}
                        Monsieur
                    {% elseif representant.sexe == 'F' %}
                        Madame
                    {% else %}
                    {% endif %}
                    {{ representant.prenom|capitalize }} {{ representant.nom|upper  }}, {{ representant.fonction|lower }}
                </p>
                <div class="signature">
                    <img src="{{ path('tampon_display', { filename: representant.tamponFilename }) }}" alt="le tampon et la signature du représentant">
                </div>
            </div>
        </div>
    
        <p class="doc-footer">
            {{ representant.prenom|capitalize }} {{ representant.nom|upper  }}, Diététicienne-Qualiticienne - N° SIRET : {{ entreprise.numSiret }} - Tel : {{ entreprise.tel }}<br>
            Activité enregistrée sous le n° {{ entreprise.numDeclaActivite }} auprès de la région {{ entreprise.prefectureRegion }}
        </p>

    </div>

</div>

{% endblock %}

templates/document/attestation_fin_formation.html.twig
{% extends 'base03.html.twig' %}

{% block title %}Document administratif : attestation de formation professionnelle{% endblock %}

{% block meta_description %}Le document administratif 'attestation de fin de formation' généré automatiquement par FORMA'GESTION pour chaque apprenant ayant participé à une session.{% endblock %}

{% block body %}

<div class="accueil-sous-cont">

    {# logo du haut de la page #}
    <div class="doc-header">
        {% if entreprise is not null and entreprise.logoFilename is not empty %}  {# on ajoute une vérification pour éviter une erreur si l'entreprise n'existe pas ou si le logo n'est pas encore choisi #}
            <img src="{{ path('logo_display', { filename: entreprise.logoFilename }) }}" alt="Logo de l'entreprise {{ entreprise.raisonSociale }}">
        {% endif %}
    </div>

    <h1>ATTESTATION DE FORMATION PROFESSIONNELLE</h1>

    <div class="sous-cont">
        
        <p class="saut-ligne">
            Je 
            {% if representant.sexe == 'M' %} 
                soussigné, 
            {% elseif representant.sexe == 'F' %} 
                soussignée, 
            {% else %} 
                soussigné(e), 
            {% endif %}, 
            {{ representant.prenom|capitalize }} {{ representant.nom|upper  }},<br>
            agissant en qualité de {{ representant.fonction|lower }} de la société {{ entreprise.raisonSociale }}, organisme de formation dont la déclaration d'activité est enregistrée sous le numéro {{ entreprise.numDeclaActivite }} auprès du préfet de la région {{ entreprise.prefectureRegion }},
        </p>
    
        <p class="saut-ligne">
            atteste que :
        </p>
    
        <p class="saut-ligne">
            {% if apprenant.sexe == 'M' %}
                Monsieur
            {% elseif apprenant.sexe == 'F' %}
                Madame
            {% else %}
                L'apprenant
            {% endif %}
            {{ apprenant.prenom|capitalize }} {{ apprenant.nom|upper }},<br>
            {% if societe is not null %}
                {% if apprenant.sexe == 'M' %}
                    salarié
                {% elseif apprenant.sexe == 'F' %}
                    salariée
                {% else %}
                    salarié(e)
                {% endif %} de l'entreprise {{ societe.raisonSociale }},<br>
            située au {{ societe.adresseSiege }} - {{ societe.codePostalSiege }} {{ societe.villeSiege }},<br>
            {% endif %}
        </p>
        
        <p class="saut-ligne">
            a suivi la formation :
        </p>
    
        <h2>{{ session.formation.nomFormation }}</h2>
    
        <p class="saut-ligne">
            qui s'est déroulée {{ session.datesSession }}, pour une durée de {{ session.formattedDuration }}.
        </p>
    
        <div>
            <p class="saut-ligne">
                La formation a été animée par :<br>
                {% for encadrement in session.encadrements %}
                    {{ encadrement.formateur.prenom|capitalize }} {{ encadrement.formateur.nom|upper }} en tant que référent {{ encadrement.typeReferent|lower }},<br>
                {% endfor %}
    
            </p>
            <p class="saut-ligne">
                à l'adresse suivante :
            </p>
            <ul class="saut-ligne">
                <li>
                    {% if societe is defined %}{{ societe.adresseSiege }} {{ societe.codePostalSiege }} {{ societe.villeSiege|capitalize }} {{ societe.paysSiege|upper }}{% else %}au domicile de {{ apprenant.prenom|capitalize }} {{ apprenant.nom|upper }}{% endif %}
                </li>
            </ul>
        </div>
    
        <h3>
            Nature de l'action :
        </h3>
        <p>
            Action d'adaptation et de développement des compétences des salariés.
        </p>
    
        <h3>
            Objectifs de la formation :
        </h3>
        <p>
            {{ session.formation.programme.objectifsPeda }}.
        </p>
    
        <h3>
            Résultats de l'évaluation des acquis de la formation :
        </h3>
        <p>
            Les compétences nécessaires à l'atteinte des objectifs sont acquises par le stagiaire.
        </p>
    
        <div class="saut-ligne">
            Fait à {{ entreprise.villeSiege|capitalize }}, le {{ 'now'|date("d-m-Y") }}
        </div>
    
        <div class="signatures saut-ligne">
            <div>
                <p>
                    Signature de<br>
                    {% if apprenant.sexe == 'M' %}
                        Monsieur
                    {% elseif apprenant.sexe == 'F' %}
                        Madame
                    {% else %}
                        L'apprenant
                    {% endif %}
                    {{ apprenant.prenom|capitalize }} {{ apprenant.nom|upper }}                 
                </p>
                <div class="signature"></div>
            </div>
            <div>
                <p>
                    Cachet et signature<br>
                    du responsable du dispensateur de formation<br>
                    {% if representant.sexe == 'M' %}
                        Monsieur
                    {% elseif representant.sexe == 'F' %}
                        Madame
                    {% else %}
                    {% endif %}
                    {{ representant.prenom|capitalize }} {{ representant.nom|upper  }}, {{ representant.fonction|lower }}
                </p>
                <div class="signature">
                    <img src="{{ path('tampon_display', { filename: representant.tamponFilename }) }}" alt="le tampon et la signature du représentant">
                </div>
            </div>
        </div>
    
        <p class="doc-footer">
            {{ representant.prenom|capitalize }} {{ representant.nom|upper  }}, Diététicienne-Qualiticienne - N° SIRET : {{ entreprise.numSiret }} - Tel : {{ entreprise.tel }}<br>
            Activité enregistrée sous le n° {{ entreprise.numDeclaActivite }} auprès de la région {{ entreprise.prefectureRegion }}
        </p>

    </div>

</div>

{% endblock %}

templates/document/attestation_fin_formation_pdf.html.twig
{% extends 'base04.html.twig' %}

{% block title %}Document administratif : attestation de formation professionnelle{% endblock %}

{% block meta_description %}Le document administratif 'attestation de fin de formation' au format PDF généré automatiquement par FORMA'GESTION pour chaque apprenant ayant participé à une session.{% endblock %}


{% block pdf_header %}
<div class="cont-logo-base64">
    <img src="{{ logoBase64 }}" alt="Logo de l'entreprise {{ entreprise.raisonSociale }}">
</div>
{% endblock %}


{% block body %}

<h1>ATTESTATION DE FORMATION PROFESSIONNELLE</h1>

<p>
    Je 
    {% if representant.sexe == 'M' %} 
        soussigné, 
    {% elseif representant.sexe == 'F' %} 
        soussignée, 
    {% else %} 
        soussigné(e), 
    {% endif %}, 
    {{ representant.prenom|capitalize }} {{ representant.nom|upper  }},<br>
    agissant en qualité de {{ representant.fonction|lower }} de la société {{ entreprise.raisonSociale }}, organisme de formation dont la déclaration d'activité est enregistrée sous le numéro {{ entreprise.numDeclaActivite }} auprès du préfet de la région {{ entreprise.prefectureRegion }},
</p>

<p>
    atteste que :
</p>

<p>
    {% if apprenant.sexe == 'M' %}
        Monsieur
    {% elseif apprenant.sexe == 'F' %}
        Madame
    {% else %}
        L'apprenant
    {% endif %}
    {{ apprenant.prenom|capitalize }} {{ apprenant.nom|upper }},<br>
    {% if societe is not null %}
        {% if apprenant.sexe == 'M' %}
            salarié
        {% elseif apprenant.sexe == 'F' %}
            salariée
        {% else %}
            salarié(e)
        {% endif %} de l'entreprise {{ societe.raisonSociale }},<br>
    située au {{ societe.adresseSiege }} - {{ societe.codePostalSiege }} {{ societe.villeSiege }},<br>
    {% endif %} 
</p>

<p>
    a suivi la formation :
</p>

<h2>{{ session.formation.nomFormation }}</h2>

<p>
    qui s'est déroulée {{ session.datesSession }}, pour une durée de {{ session.formattedDuration }}.
</p>

<div>
    <p>
        La formation a été animée par :<br>
        {% for encadrement in session.encadrements %}
            - {{ encadrement.formateur.prenom|capitalize }} {{ encadrement.formateur.nom|upper }} en tant que référent {{ encadrement.typeReferent|lower }},<br>
        {% endfor %}

    </p>
    <p>
        à l'adresse suivante : {% if societe is not null %}{{ societe.adresseSiege }} {{ societe.codePostalSiege }} {{ societe.villeSiege|capitalize }} {{ societe.paysSiege|upper }}{% else %}au domicile de {{ apprenant.prenom|capitalize }} {{ apprenant.nom|upper }}{% endif %}
    </p>
</div>

<h3>
    Nature de l'action : <span class="paragraf">action d'adaptation et de développement des compétences des salariés</span>
</h3>

<h3>
    Objectifs de la formation :
</h3>
<p>
    {{ session.formation.programme.objectifsPeda }}.
</p>

<h3>
    Résultats de l'évaluation des acquis de la formation :
</h3>
<div> 
    <div class="reponse02">&nbsp;</div>
</div>

<div class="saut-ligne">
    Fait à {{ entreprise.villeSiege|capitalize }}, le {{ 'now'|date("d-m-Y") }}
</div>

<div class="signatures saut-ligne">
    <div>
        <p>
            Signature de<br>
            {% if apprenant.sexe == 'M' %}
                Monsieur
            {% elseif apprenant.sexe == 'F' %}
                Madame
            {% else %}
                L'apprenant
            {% endif %}
            {{ apprenant.prenom|capitalize }} {{ apprenant.nom|upper }}                 
        </p>
        <div class="signature"></div>
    </div>
    <div>
        <p>
            Cachet et signature<br>
            du responsable du dispensateur de formation<br>
            {% if representant.sexe == 'M' %}
                Monsieur
            {% elseif representant.sexe == 'F' %}
                Madame
            {% else %}
            {% endif %}
            {{ representant.prenom|capitalize }} {{ representant.nom|upper  }}, {{ representant.fonction|lower }}
        </p>
        <div class="signature">
            <div class="cont-tampon-base64">
                <img src="{{ tamponBase64 }}" alt="Tampon de l'entreprise {{ entreprise.raisonSociale }}">
            </div>
        </div>
    </div>
</div>
    
<div class="footer">
    <p>
    {{ representant.prenom|capitalize }} {{ representant.nom|upper  }}, Diététicienne-Qualiticienne - N° SIRET : {{ entreprise.numSiret }} - Tel : {{ entreprise.tel }}<br>
    Activité enregistrée sous le n° {{ entreprise.numDeclaActivite }} auprès de la région {{ entreprise.prefectureRegion }}
    </p>
</div>

{% endblock %}

templates/document/contrat_client_particulier.html.twig
{% extends 'base03.html.twig' %}

{% block title %}Document administratif : contrat client particulier{% endblock %}

{% block body %}



{% endblock %}

templates/document/programme.html.twig
{% extends 'base03.html.twig' %}

{% block title %}Document administratif : programme{% endblock %}

{% block body %}



{% endblock %}

templates/document/releve_connexion.html.twig
{% extends 'base03.html.twig' %}

{% block title %}Document administratif : relevé de connexion{% endblock %}

{% block body %}



{% endblock %}